### ISSUE TITLE
[PE-D] Able to add 2 patients with the same details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-1/tp#252]
![Screenshot 2021-10-29 at 4.43.48 PM.png](https://raw.githubusercontent.com/vigneshsankariyer1234567890/ped/main/files/c03c58bd-f344-4d3c-acc9-12a2ef95ff93.png)
I can add the same patient multiple times (as seen with John). 

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: vigneshsankariyer1234567890/ped#9

**Comment by simonjulianl** [comment]
as shown in the overview, there is no guarantee that john, with same contact number is the same patient
