### ISSUE TITLE
[PE-D] Scroll Speed Is a bit too high

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-1/tp#261]
![image.png](https://raw.githubusercontent.com/alyssa-savier/ped/main/files/65be606e-1934-43e7-a368-68b22eb1e38a.png)

Scroll speed of the list is a bit high which may be difficult to find patients via scrolling

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: alyssa-savier/ped#9

**Comment by yyhangz** [comment]
We feel that this is not a bug, but rather a matter of personal preference. If we were to change the scroll speed on our end, others may feel that the scroll speed is too low for their liking. 

But thanks for raising this, we may look at including a section in our UG to highlight to the users that the scroll speed for our app is fixed, so they will have to adjust the scroll speed on their own systems if it is not to their liking.
