### ISSUE TITLE
[PE-D] No way to see full description of an activity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-1/tp#281]
Description may potentially overflow but there is no way to view the full description.
Perhaps the UI could be changed in a way that makes this possible? Not sure if this would help but you could refer to JavaFX titled panes.
![Screenshot 2021-10-29 at 6.16.45 PM.png](https://raw.githubusercontent.com/nicole-luo-exe/ped/main/files/6a79aed9-61c0-4246-8822-72a07d6913f6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nicole-luo-exe/ped#9

**Comment by simonjulianl** [comment]
Hem unfortunately titled panes is from close up and down which would wont work with the table view javaFX, but ill try my best to address this issue by addressing the height
